//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.28 at 01:55:12 PM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://goodboyz.com/employeemanager", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.goodboyz.employeemanager;
